server:
  port: 8383
spring:
  application:
    name: user-service
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/springbootrestcrud_db 
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    #driver-class-name: com.mysql.cj.jdbc.Driver
    
  zipkin:
    base-url: http://localhost:9411/


eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone : http://${eureka.instance.hostname}:8761/eureka/

security:
  basic:
    enabled: false
  oauth2:
    resource:
      token-info-uri: http://localhost:8686/oauth/check_token
    client:
      client-id: javadeveloperzone
      client-secret: secret
